DROP TABLE IF EXISTS TYPE_ROOM;
CREATE TABLE TYPE_ROOM(
ID BIGINT NOT NULL,
COUNT_PLACES INT NOT NULL,
PRISE INT NOT NULL,
DESCRIPTION VARCHAR (1000) NOT NULL,
CLASS_OF_ROOM VARCHAR (100) NOT NULL,
PRIMARY KEY (ID));