drop table if exists TYPE_ROOM;
create table TYPE_ROOM(
ID BIGINT NOT NULL,
COUNT_PLACES INT NOT NULL,
PRISE INT NOT NULL,
DESCRIPRION VARCHAR (1000) NOT NULL,
CLASS_OF_ROOM VARCHAR (100) NOT NULL,
primary key (ID));