CREATE SCHEMA IF NOT EXISTS TRAIN_TICKETS;
CREATE TABLE IF NOT EXISTS TRAINS(
    ID LONG PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    SEATING INT NOT NULL,
    FREE_SEATS INT
);
TRUNCATE TABLE TRAINS;