CREATE SCHEMA IF NOT EXISTS TRAIN_TICKETS;
CREATE TABLE IF NOT EXISTS users (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255),
email VARCHAR(255),
password VARCHAR(255),
);
TRUNCATE TABLE users;

