CREATE SCHEMA IF NOT EXISTS TRAIN_TICKETS;
CREATE TABLE IF NOT EXISTS TRAINS(
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    SEATING INT NOT NULL,
    FREE INT,
    );
TRUNCATE TABLE trains;