CREATE SCHEMA IF NOT EXISTS TRAIN_TICKETS;
CREATE TABLE IF NOT EXISTS TRAINS(
    ID long NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    SEATING INT NOT NULL,
    FREE_SEATS INT,
    PRIMARY KEY (ID)
);
TRUNCATE TABLE TRAINS;