CREATE SCHEMA IF NOT EXISTS DEVELOPERS_TEAM;
CREATE TABLE IF NOT EXISTS projects (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    description VARCHAR (250),
    status VARCHAR(20),
    eta DATE,
    PRIMARY KEY (id)
);
TRUNCATE TABLE projects;