CREATE SCHEMA IF NOT EXISTS DEVELOPERS_TEAM;
CREATE TABLE IF NOT EXISTS customers (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    address VARCHAR (150),
    phone VARCHAR(20),
    PRIMARY KEY (id)
);
TRUNCATE TABLE customers;
