CREATE SCHEMA IF NOT EXISTS DEVELOPERS_TEAM;
CREATE TABLE IF NOT EXISTS managers (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR (50),
    phone VARCHAR(20),
    PRIMARY KEY (id)
);
TRUNCATE TABLE managers;