CREATE SCHEMA IF NOT EXISTS DEVELOPERS_TEAM;
CREATE TABLE IF NOT EXISTS developers (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);
TRUNCATE TABLE developers;