CREATE SCHEMA IF NOT EXISTS DEVELOPERS_TEAM;
DROP TABLE IF EXISTS tasks;
CREATE TABLE IF NOT EXISTS tasks (
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    description VARCHAR (250),
    PRIMARY KEY (id)
);
