CREATE SCHEMA IF NOT EXISTS DEVELOPERS_TEAM;
DROP TABLE IF EXISTS developers;
CREATE TABLE IF NOT EXISTS developers (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);