CREATE SCHEMA IF NOT EXISTS TRAIN_TICKETS;
CREATE TABLE IF NOT EXISTS ADMINS(
   ID BIGINT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(50) NOT NULL,
   LASTNAME VARCHAR (50) NOT NULL,
   PASSWORD VARCHAR (50) NOT NULL,
   PRIMARY KEY(ID),
);
CREATE TABLE IF NOT EXISTS TRAINS(
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    SEATING INT NOT NULL,
    FREE INT,
);
CREATE TABLE  if NOT EXISTS invoices(
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
price DECIMAL (10,2),
attributes VARCHAR (150)
);
CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR (150),
    password VARCHAR(20),
);

